### ISSUE TITLE
Where can i find "User Agent" parameter?

### ISSUE THREAD

**Issue by d-apps** [mitchhymel/dart-igdb_client#5]
Could you please tell me where can I find my User Agent?

I couldn't find it anywhere, in your example you don't show the variable value...

var client = new IGDBClient("?", API_KEY);

**Comment by mitchhymel** [comment]
The [User Agent](https://en.m.wikipedia.org/wiki/User_agent) string is a way for your app to identify itself to the IGDB servers. This can be whatever you want it to be - any string value should work here.

**Comment by d-apps** [comment]
Thank you.

**Comment by d-apps** [comment]
Could you please explain me how to pass each game found in gamesResponse.data to a Game class to show to the user?

class Game {

  String id;
  String name;
  String cover;
  String storyline;
  List<String> screenshots;

}

 And how do I access and show fields with numbers, like:

 "screenshots": [
 25285,
 25286
 ]

"id": 19678,

class Game {

  String id;
  String name;
  String cover;
  String storyline;
  List<String> screenshots;

}

**Comment by mitchhymel** [comment]
I have a "work in progress but I kinda stopped working on it for now" app that was the motivation for creating this library which you can check out [here](https://github.com/mitchhymel/gamendar):

As for some code relevant to your question...
Check out [here](https://github.com/mitchhymel/gamendar/blob/master/lib/src/services/game_service_client.dart#L36) showing how I use igdb_client to fetch the data and what params I use. 
Then check [here](https://github.com/mitchhymel/gamendar/blob/master/lib/src/services/models/game.dart#L44) for how I convert the response's map object to my own data class. JSON serialization/deserialization in flutter is not as nice as other languages so I just did this manually as can be seen in the fromMap method.

**Comment by d-apps** [comment]
I just made a question about IGDB on stackoverflow about this hehe, thank you for the links, it will help me a lot. I am new to APIs, this is my first project using one.

**Comment by d-apps** [comment]
@mitchhymel Is the quality so low for cover and screenshots? all them have 90x90 px, looks ugly in the app :/ and I didn't find some games or they don't have cover or screen.

**Comment by mitchhymel** [comment]
I'd suggest reading [IGDB's API docs](https://api-docs.igdb.com/#images) to understand how they handle images and to ultimately understand why igdb_client handles images the way it does.

The reason you're seeing the 90x90px images is because that is the default unless you specify a size.

The [igdb_client provides helpers](https://github.com/mitchhymel/dart-igdb_client/blob/master/lib/src/igdb_helpers.dart#L11) to get image urls of specific quality provided the image id and quality enum.

You can also view [my app's code](https://github.com/mitchhymel/gamendar/blob/master/lib/src/utils/asset_helper.dart#L10) as an example of this being used in practice.
